name: EQ_gates_passing_probabilities
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - pip
  - pip:
    - matplotlib-transforms 
